Rails Blog app - controllers specs
killy10o10/rails-blog pull request #5
Opened 2022-12-15 19:09 UTC by killy10o10

# Description:
In this feature, I set up tests on the controllers I recently added to the Rails Blog app.

## Completed the following Project requirements
- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
    - If response status was correct.
    - If a correct template was rendered.
    - If the response body includes correct placeholder text.

## Happy Reviewing!!😁🥳🥂

2022-12-15 19:28 UTC, Ismailco requested changes
### Hi @killy10o10, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 19:28 UTC, Ismailco commented on spec/requests/posts_spec.rb
> +        expect(response.body).to include('List all users posts')
- [ ] Kindly make sure to include tests that ensure the correct view template is rendered, as you did in the other action test. e.g `expect(response).to render_template('index')`

2022-12-15 19:28 UTC, Ismailco commented on spec/requests/users_spec.rb
>    describe 'GET /index' do
- [ ] To Not repeat yourself and follow the best practices kindly make sure to combine your tests in one `Rspec. describe....`

2022-12-15 19:28 UTC, Ismailco commented on spec/requests/users_spec.rb
> +      expect(response).to render_template('index')
- [ ] Great job creating the tests for users requests however you should include tests that ensure the response body includes the correct placeholder text, you did this in the next test but kindly make sure to include it also in this test. e.g `expect(response.body).to include(.....)`

2022-12-15 19:28 UTC, Ismailco commented on spec/requests/posts_spec.rb
> +        expect(response).to render_template('show')
- [ ] Great job creating the tests for `posts` requests however you should include tests that ensure the response body includes the correct placeholder text, you did this in the previous test but kindly make sure to include it also in this test. e.g `expect(response.body).to include(.....)`

2022-12-16 00:15 UTC, mwanawabangona approved these changes
Hi @killy10o10 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 00:43 UTC, merged